### ISSUE TITLE
Minor JSON serialization deserialization issue with numeric indices

### ISSUE THREAD

**Issue by DarkholmeTenk** [MWSE/MWSE#100]
If you have a lua table like `{[0] = "A", b="B"}` this will serialize to `{"0":"A","b":"B"}` which is roughly what you'd expect, but then deserializes to `{["0"] = "A", b="B"}`.

Any lua numeric key when serialized becomes a string because json objects can't have numeric keys and then deserializes back to a string key.

Fully expect this to be closed as Wont-Fix because it's the most insignificant edge case, but perhaps a note should be made in documentation somewhere about this behaviour.

**Comment by C3pa** [comment]
This is now documented. In addition, `mwse.loadConfig` will reconstruct the returned config table if it was given the `default` table.
