### ISSUE TITLE
[request] A way to lock a door reference not yet locked/unlocked from LUA

### ISSUE THREAD

**Issue by abitoftaste** [MWSE/MWSE#109]
I'd like a way to lock a door reference not yet locked/unlocked from LUA
as I understand changing locked property to true does not create a lockNode if needed like standard Morrowind scripting Lock command does.
I think  added internally to .locked property = true would be simpler/faster to use, but using a new LUA Lock() method could include also lock value/be more similar to standard Morrowind Lock function.
I would use it to try making a linked door auto lock synchronization mod.

**Comment by NullCascade** [comment]
Which implementation do you (and others) prefer:

This:
```lua
tes3.lock(reference)
tes3.unlock(reference)
tes3.setTrap(reference, spell)
tes3.removeTrap(reference)
tes3.getLockLevel(reference)
tes3.getLocked(reference)
```

Or this:
```lua
local lock = tes3.getLock(reference)
if (lock == nil or lock.locked == false) then
    tes3.setLock({ reference = reference, locked = true, level = 25, trap = trapSpell })
end
```

**Comment by abitoftaste** [comment]
Personally I prefer the first one as it is more similar to standard Morrowind scripting, but it does not matter much as second one using LUA tables style is widely present already

**Comment by NullCascade** [comment]
Added functions in 153b7c1ff21b04de7f4f5abf831615ca0d797789. Will close issue when docs are added.
