### ISSUE TITLE
xGetRegion 

### ISSUE THREAD

**Issue by Greatness7** [MWSE/MWSE#11]
This function would be nice to have. I've often seen requests for stuff like regional shaders, regional music, regional survival mechanics, etc. Currently there's no good way to handle those as the "CellID" functions just return "Wilderness" for every region. 

```
setx regionID gridX gridY to ref->xGetRegion
xMessageFix "%s (%d, %d)" regionID gridX gridY
MessageBox "________________________________ (____, ____)"
```

The X/Y would be a nice addition, but if they're not easily obtainable we can put them off for later. (MWSE allows optional returns)

**Comment by NullCascade** [comment]
This can be done in Lua now.
