### ISSUE TITLE
Disposition changes to NPCs not permanent

### ISSUE THREAD

**Issue by MortimerMcMire** [MWSE/MWSE#112]
local dialogMenu = tes3ui.findMenu(tes3ui.registerID("MenuDialog"))
local actor = dialogMenu:getPropertyObject("PartHyperText_actor")
actor.reference.object.disposition = 90

the disposition is changed in the dialogue and everything works there, but when you close the dialogue window the disposition resets to the base value.

**Comment by NullCascade** [comment]
Fixed in b9db8961a38228aea1b6020988e0ae0c95478916. Let me know if you encounter further issues with this.
