### ISSUE TITLE
Selling some items causes CTD

### ISSUE THREAD

**Issue by lightsourced** [MWSE/MWSE#113]
When trying to sell the Tax Record (ID- bkseydaneentaxrecord) to Arille I get a CTD. There have been other reports of similar things happening on the nexus posts (https://www.nexusmods.com/morrowind/mods/45468?tab=posts) - see below: 

"Latest version is causing a crash when I sell certain items after creating a new game, specifically the Iron Dagger, and the directions and package for Caius Cosades. Sorry to report this here rather than github." - jcArd

**Comment by NullCascade** [comment]
Fixed in 5d59e5e955a99252bd6b2fb22aeed2b1388ed380.

I've pushed an early daily build. Run MWSE-Updater and the issue should go away. Thanks for reporting this here.

**Comment by lightsourced** [comment]
Thank you!!
