### ISSUE TITLE
Fade in / Fade out function

### ISSUE THREAD

**Issue by MortimerMcMire** [MWSE/MWSE#119]
When training you get a quick fade in / fade out to indicate passage of time
maybe as a wrapper for the mwscript function

**Comment by NullCascade** [comment]
Added some functions, `tes3.fadeIn`, `tes3.fadeOut`, and `tes3.fadeTo`.

These are based on the mwscript functions, but aren't wrappers. The default fade time is 1 second.

Usage:
```lua
-- Fades out over 1 second, then after 0.5 seconds will fade in for 1 second.
local function fadeOutThenIn(e)
    tes3.fadeOut()
    timer.start({ type = timer.real, duration = 1.5, callback = tes3.fadeIn })
end
```

Duration and alternative faders can be set too:
```lua
-- Use the hit fader for 0.5 (same as when taking damage).
local function fadeHit(e)
    tes3.fadeIn({ fader = tes3.worldController.hitFader, duration = 0.5 })
end
```

Valid faders are `tes3.worldController.transitionFader` (default), `tes3.worldController.blindnessFader`, `tes3.worldController.sunglareFader`, `tes3.worldController.hitFader`, and `tes3.worldController.werewolfFader`.

Support for custom faders will happen at some point, but I'll leave that to another issue.
