### ISSUE TITLE
xPickUp request

### ISSUE THREAD

**Issue by svengineer99** [MWSE/MWSE#12]
This would be to inverse of xDrop - move a world reference object into an actor's inventory.  

Related requests, lower priority, if possible:
- xDrop returns the reference of the dropped item (otherwise have to scan the cell for it)
- xDrop and xPickUp working for containers would be brilliant, too.

**Comment by Greatness7** [comment]
+1 this is definitely one of the MWSE dream features that have been wanted for a long time.

A more accurate name for it would likely be `xOnActivate`. NullCascade did some work on trying to implement it a few weeks ago, but I can't remember how feasible it looked to be.

Just as a refresher: Currently `ref->Activate` _does_ technically work, but it requires the vanilla `OnActivate` condition to be fulfilled before calling it, which we have no good way to do through MW script.

According to Hrnchmad, OnActivate works like this:

> [7:49 PM] Hrnchamd: If you use OnActivate it caches the last actor to activate it.
[7:50 PM] Hrnchamd: Then Activate will work at any time with the cached actor.

So in theory all that needs to be done is find a way to set manually set this cache in memory.

**Comment by NullCascade** [comment]
e4566148b92557a418decea364b644b1335a6c22 adds xActivate.

Usage:
```
someActor->xActivate someRef
```
This causes `someActor` to pick up/use `someRef`.

Does this satisfy the `xPickUp` request? `xDrop` and `xTransfer` would be viable functions to add in the future.

**Comment by NullCascade** [comment]
Redundant with `xActivate`. Closing.
