### ISSUE TITLE
Random crash when reloading a save

### ISSUE THREAD

**Issue by Irv1n3** [MWSE/MWSE#121]
When I'm loading a save while I'm already in-game, a crash can happen.
Not a high reproduce rate but I attach the dump if you can see relevant information in it.
[MWSE dump loading.zip](https://github.com/MWSE/MWSE/files/2431015/MWSE.dump.loading.zip)

**Comment by NullCascade** [comment]
This looks like a vanilla crash, but maybe one of your mods is doing something unexpected with the UI features. Are you using any GUI related mods? Does the crash go away if you remove those mods?
