### ISSUE TITLE
Events for Dialogue filtering and text changes

### ISSUE THREAD

**Issue by jhaakma** [MWSE/MWSE#122]
-- Event fired when INFO conditions are being tested.
local function onTestConditions(e)
    -- Only show this entry on Wednesdays.
    e.pass = (os.date("*t").wday == 4)
end

local daysOfTheWeek = { "Sunday", "Monday", "Tuesday", "Wednesday", "Thrusday", "Friday", "Saturday" }

local function onGetInfoText(e)
    -- Override the response with our custom text.
    e.text = string.format("It's %s, my dudes.", daysOfTheWeek[os.date("*t").wday])
end

local function onInitialized()
    -- Get our info. We have to wait until the game is initialized so we can find the object.
    local myInfo = tes3.getDialogueInfo({ dialogue = "Addhiranirr", id = "31446240571567215557" })
    event.register("infoTest", onTestConditions, { filter = myInfo })
    event.register("infoText", onGetInfoText, { filter = myInfo })
end
event.register("initialized", onInitialized)

**Comment by NullCascade** [comment]
cec242522b88361ebc86d4caa81b03c8d604a7da adds the infoGetText event, one half of this request.
