### ISSUE TITLE
Optional flag in activate function to bypass activate event

### ISSUE THREAD

**Issue by jhaakma** [MWSE/MWSE#126]
Specifically useful for activator scripts that activate the object in a message box called inside the activate event.

**Comment by OperatorJack** [comment]
You can bypass any event by returning false from within the event. This will block the event from occurring and prevent other event handlers from accessing the event. If you want to only block the event from other mods, you can set `e.claim = true`.

We are cleaning up issues without recent activity, so if this does not answer your questions, please let me know and I will reopen the issue.
