### ISSUE TITLE
[feature request] Enable Spell Reference in ProjectileExpired Event

### ISSUE THREAD

**Issue by Madcliff** [MWSE/MWSE#127]
Would it be possible to expose the spell object for ProjectileExpired event. Currently you can only get the weapon reference.

**Comment by C3pa** [comment]
Isn't this one fixed [https://mwse.readthedocs.io/en/latest/lua/event/projectileExpire.html](https://mwse.readthedocs.io/en/latest/lua/event/projectileExpire.html) ?

**Comment by C3pa** [comment]
Is e.mobile.object what you need?

**Comment by C3pa** [comment]
You can do e.mobile.reference to get the associated tes3spell object or e.mobile.spellInstance to get the associated tes3magicSourceInstance object.
