### ISSUE TITLE
UI expansion bug - topics journal is broken

### ISSUE THREAD

**Issue by leevys** [MWSE/MWSE#132]
Some problems with dialogues in UI Expansion:

1. In order for topic to grey out you have to click in the topics menu, is doesn't working with clicking in the main menu of dialogue.

2. Often, when I see new colored topic (not-blue) and click on it, NPC says old phrase, but in journal recorded new phrase, which I've never seen before.

3. Topics are dissapearing from journal after restart of the game. Not all of them, like 20-30%. For example, I walked around Balmora, talked with people, collected 14 pages of "Morrowind lore" quotes, and in the next day I had only 10 pages (most frustraiting for me).

Problem in the MWSE / UI Expansion - tried on absolutely clean Morrowind, topics does not disappearing.

**Comment by OperatorJack** [comment]
Hi @leevys, UI Expansion is a mod that uses MWSE and is not part of the MWSE project. If you are still experiencing these issues, you should open an issue on the appropriate repository, which is [Nullcascade's Morrowind Mods Repository](https://github.com/NullCascade/morrowind-mods).
