### ISSUE TITLE
Enchanted items losing all charges on reload

### ISSUE THREAD

**Issue by JayRust** [MWSE/MWSE#140]
Even with a clean install, using nothing but MGE XE and MGSE, all enchanted items lose their charges after reloading a saved game. This happens 100% of the time. I could have a full-charged Fargoth's Ring equipped, quicksave and then immediately quickload, and it'll become empty of charges and unusable. I tried reinstalling again, this time without using MGSE at all, and functionality returned to normal.

**Comment by NullCascade** [comment]
This should be fixed in d08f8f9c090ef15f57c381deb96fa51718f9f664. I've pushed an update, please run MWSE-Updater and let me know if this is fixed.

**Comment by JayRust** [comment]
Yes, it's perfect! Thank you very much!

**Comment by NullCascade** [comment]
Excellent. Thank you for reporting this issue.
