### ISSUE TITLE
UI Expansion Mod seems to stop working with MWSE error

### ISSUE THREAD

**Issue by strangealien** [MWSE/MWSE#142]
How to repeat: In the spells menu filter for Illusion (for example). Now select a Illusion spell and hold SHIFT, so that the spell will be deleted. The confirmation window comes up, confirm and the spell is deleted. But from this point on you have no filters in your spell list, the UI expansion stopped working. Reload will fix this.

Here is the log file MWSELog.txt:
Morrowind Script Extender v2.1.0 (built Dec 17 2018) hooked.
Found MGE XE. Version: 0.10.1.0
MWSE Lua interface initialized.
[UI Expansion] Loaded configuration:
{
  "version":1,
  "mapConfig":{
    "minY":-59,
    "maxY":29,
    "minX":-142,
    "cellResolution":9,
    "autoExpand":true,
    "maxX":70
  },
  "autoSelectInput":"Magic",
  "keybindTakeAll":[29,57],
  "showHelpText":true,
  "dialogueTopicSeenColor":"journal_finished_quest_color",
  "useInventoryTextButtons":true,
  "selectSpellsOnSearch":true,
  "keybindClose":[57],
  "autoFilterToTradable":false,
  "takeFilteredItems":true,
  "components":{
    "options":true,
    "dialog":true,
    "inventorySelect":true,
    "magic":true,
    "stat":true,
    "journal":false,
    "contents":true,
    "inventory":true,
    "barter":true,
    "map":false
  },
  "dialogueTopicUniqueColor":"link_color"
}
Initialized UniqueTooltips
Initialized KeyTooltips v0.00
[UI Expansion] Skipping module: map
Initialized QuestTooltips
Initialized ArtifactTooltips
Initialized IndexTooltips
Error in event callback: Data Files/MWSE/mods/UI Expansion/MenuOptions.lua:5: attempt to index field 'texture' (a nil value)
stack traceback:
	./Data Files/MWSE/core/event.lua:141: in function <./Data Files/MWSE/core/event.lua:129>

I have the following MWSE mods installed:
MWSE Unique Items tooltips
MWSE Key tooltips
MWSE UI Expansion

MWSE is the latest version from MWSE-update.exe.

**Comment by strangealien** [comment]
Happened again, this time without UI open, just running along.
This time the game crashed, log and crash dump are appended.

**Comment by Petethegoat** [comment]
See discussion here instead: https://github.com/NullCascade/morrowind-mods/issues/23
