### ISSUE TITLE
Music related functions

### ISSUE THREAD

**Issue by Rytelier** [MWSE/MWSE#146]
Requests for music playing and managing related function:
- Get current playing music file path
- Get current time position of current music track
- Play/jump to certain position at music track
- Switch to set music not being interrupted by save load screen - music will continue playing instead of restarting when loading a save ingame

**Comment by NullCascade** [comment]
Added some of this. You can read information now off of the audio controller:
```lua
local function showAudioInformation()
	local ac = tes3.worldController.audioController
	mwse.log("Current track: %s (%.2f / %.2f)", ac.currentMusicFilePath, ac.musicPosition, ac.musicDuration)
	mwse.log("Next track: %s", ac.nextMusicFilePath)
	mwse.log("   Starts at %s, fade of %s, with volume of %.2f", ac.musicNextTrackStartTimestamp, ac.musicFadeBeginTimestamp, ac.musicNextTrackVolume)
	mwse.log("Volumes - Master: %.2f, Music: %.2f, Effects: %.2f, Footsteps: %.2f, Voice: %.2f", ac.volumeMaster, ac.volumeMusic, ac.volumeEffects, ac.volumeFootsteps, ac.volumeVoice)
	mwse.log("Location: %s, Pitch Axis: %s, Yaw Axis: %s", ac.listenerPosition, ac.pitchAxis, ac.yawAxis)
end
```

You can also seek by setting `ac.musicPosition`. E.g., you can rewind by 1 second using:
```lua
local function rewindMusic1Second()
	local ac = tes3.worldController.audioController
	ac.musicPosition = math.max(ac.musicPosition - 1, 0)
end
```

The only thing not implemented is the change in music behavior when loading a game. Can you explain your need for this? It seems like it'd be pretty strange behavior.
