### ISSUE TITLE
Enchantment functions

### ISSUE THREAD

**Issue by svengineer99** [MWSE/MWSE#148]
- remove (detach) enchantment to an object id (that has one)
- add (attach) enchantment to an object id (that doesn't have one already)
- create encahntment (like tes3spell.create)
- set enchantment flag to save changes (default seems unflagged; similar to spell origin =1 (not saved) vs origin=2 (saved)

**Comment by OperatorJack** [comment]
* Enchantments can be removed from an object by getting the object using `tes3.getObject()`, getting the enchantment using `tes3.getObject()`, and then setting the `.enchantment` property of the object.
* Enchantments can be added to an object by setting the `.enchantment` property of the object using the method above.
* Creating enchantments is now supported via `tes3enchantment.create()`. It is best to check for existence and reinitialise the enchantment object each time Morrowind is started.

We are cleaning up issues without recent activity, so if this does not answer your questions, please let me know and I will reopen the issue.

**Comment by svengineer99** [comment]
Awesome!  This will definitely enable improvement and simplification for the identification/enchanted items mod I had started on with MWSEscript, needs a complete re-write in lua now.  THANK YOU!
