### ISSUE TITLE
get/set/modEffect for LUA

### ISSUE THREAD

**Issue by Wolvman92** [MWSE/MWSE#153]
Would be great to be able to check for things like sEffectFortifyAttribute and return the magnitude of the effect.

Additionally, being able to adjust the value of the effect on the fly would be very helpful.

**Comment by OperatorJack** [comment]
You can now check if an actor is affected by an effect with the API function `tes3.isAffectedBy()`. You can check the magnitude that actor is affected by with the API function `tes3.getEffectMagnitude()`. Refer to the documentation for additional information on each API function.
