### ISSUE TITLE
Have attackSwing give its value as soon as a weapon is pulled back

### ISSUE THREAD

**Issue by DenverNova** [MWSE/MWSE#156]
Right now attackSwing only has a value once an attack is released. If it was changed to give its value as soon as a weapon begins to be pulled back it would allow us to detect when an attack begins among other things. Very useful for mods that need to know how far a weapon has been pulled back at any given time.

**Comment by C3pa** [comment]
You can use [`attackStart`](https://mwse.github.io/MWSE/events/attackStart/) event.
