### ISSUE TITLE
xContentListFiltered enhancement request [withdrawn]

### ISSUE THREAD

**Issue by svengineer99** [MWSE/MWSE#16]
Could it be possible to return all items except those defined by a negative filter, such as filter=-4194304 returning all non-enchanted items?

**Comment by NullCascade** [comment]
What would be the intended behavior for this with regards to scripted/enchanted items?

If you request -2097152, should it only return enchanted non-weapons?

**Comment by svengineer99** [comment]
That's a good question.  If -4194304 returns all but enchanted items then -2097152 I would have thought could return all but weapons.  I haven't tested but I guess (4194304+2097152) should return all enchanted items or weapons?  In that case -(4194304+2097152) could return all but (enchanted items or weapons).

Anyways, it's not an essential request, just saving a conventional inventory loop in some special cases (such as wanting to separate out all non-enchanted items when opening an enchanted item service window).  Maybe I should retract it, save your time for more valuable work.

**Comment by svengineer99** [comment]
Withdrawn as explained above.
