### ISSUE TITLE
Call InventorySelect and SpellSelect menus and retrieve the result

### ISSUE THREAD

**Issue by jhaakma** [MWSE/MWSE#162]
Call the menu where items can be filtered and selected, and return the item selected by the player. Same with the select magic/spells menu .

**Comment by NullCascade** [comment]
Added `tes3.showInventorySelectMenu` in 757212f2b089653fbd2d89510da0f6d16b6f0f4f.

Spell selection will require a custom solution.

**Comment by jhaakma** [comment]
Can we get this merged into master?

**Comment by NullCascade** [comment]
This and a few other things were cherry picked into master with a0f5a1191fb055cca91f014e8e495fe82505a654.
