### ISSUE TITLE
createTextSelect and createButton widget properties

### ISSUE THREAD

**Issue by qqqbbb** [MWSE/MWSE#178]
Why are they write only?

**Comment by NullCascade** [comment]
Which properties are you talking about?

**Comment by qqqbbb** [comment]
Every widget property except 'state' is write only.

**Comment by C3pa** [comment]
These properties aren't read-only anymore:
https://mwse.github.io/MWSE/types/tes3uiButton/
https://mwse.github.io/MWSE/types/tes3uiTextSelect/
