### ISSUE TITLE
Containers from mods unlocked with tes3.unlock stay unlocked after reloading

### ISSUE THREAD

**Issue by qqqbbb** [MWSE/MWSE#183]
Steps to reproduce the bug:
1. Using CS place a new container in a cell
2. Lock the container
3. Load the game
4. Unlock the container using tes3.unlock
5. The container will be unlocked when you reload the game

**Comment by qqqbbb** [comment]
Fixed by setting the reference modified flag to true.

**Comment by NullCascade** [comment]
Fixed in a07f589470cfeedfebff7d0cc02b404e52ee9576
