### ISSUE TITLE
expose script text in tes3.script

### ISSUE THREAD

**Issue by qqqbbb** [MWSE/MWSE#186]
Would  be useful to see what a local script does so you can decide should your lua script touch that reference or not.

**Comment by NullCascade** [comment]
Parsing a mwscript file with lua sounds like it could very easily backfire. Can you elaborate on what you're trying to do here? The script text nor the offset to the record in the master file is not saved on the TES3::Script object, so it'd be a rather involved affair to go dig it back up without a good reason to.

**Comment by qqqbbb** [comment]
In animated containers mod I want to check if local script on a container has "onactivate == 1" or "activate" line. If it does not then it should be safe to call 'activate' lua command on it without breaking any quests.

**Comment by qqqbbb** [comment]
It also would be useful to see if a certain object ID is used in any scripts.

**Comment by C3pa** [comment]
You add a local variable to the script attached to your containers. Then, you can read the script's variable value from MWSE.

**Comment by C3pa** [comment]
Implemented in: https://github.com/MWSE/MWSE/commit/98a24102d17f3fa32ada13fa3a3dc5deac68fb0a#diff-e171dddf6faffe9dd04f81252357ba69e7c382e9f2b23ff6afa36aaec3f9c87aR3.
