### ISSUE TITLE
tes3vector3:rotate

### ISSUE THREAD

**Issue by qqqbbb** [MWSE/MWSE#187]
Need function to rotate tes3vector3.

**Comment by NullCascade** [comment]
Can you provide more information about your needs? Rotate it around what point? What default point should be rotated around? This seems out of scope for tes3vector3 as well, as wouldn't you want orientation to also be rotated?

What use case are you trying that would be aided by a helper function?

**Comment by qqqbbb** [comment]
I have a reference's position and its bounding box. I need to rotate bounding box min and max vectors according to the reference's orientation.
