### ISSUE TITLE
mwse.log()  error in log

### ISSUE THREAD

**Issue by qqqbbb** [MWSE/MWSE#191]
When mwse.log()  is run with bad arguments, the error message in the log does not tell you the name of the file that did it.

**Comment by NullCascade** [comment]
Can you please provide example code that triggers this error? It gives a valid stack trace to me.

**Comment by qqqbbb** [comment]
I mean usually error message in the log gives you the path to the file and the line number. But if one of lua mods has this line "mwse.log(' %d', 'q')", you cant trace it.

**Comment by NullCascade** [comment]
I tested that and it works just fine. Can you post a more complete example of what issue you're having?

**Comment by qqqbbb** [comment]
if I put "mwse.log('%d', 'q')" in any part of lua code, I get this in my log:

Error in event callback: Data Files/MWSE/core/mwse_init.lua:318: bad argument #1 to 'format' (number expected, got string)
stack traceback:
	./Data Files/MWSE/core/event.lua:148: in function <./Data Files/MWSE/core/event.lua:136>

The file with the bad command is not mentioned.
