### ISSUE TITLE
Missing in documentation

### ISSUE THREAD

**Issue by qqqbbb** [MWSE/MWSE#196]
'include' function
mwscript.setDelete
mobileActor.isDead 
tes3ui.showInventorySelectMenu
table.empty
tes3.isAffectedBy
tes3skill
tes3.player.object.factionIndex
reference:disable()
reference:enable()
reference.destination
tes3.worldController
tes3ui.updateEnchantingMenu()
tes3ui.updateSpellmakingMenu()
tes3.mobilePlayer
tes3.mobilePlayer:updateOpacity()
tes3ui.refreshTooltip()
tes3.showRestMenu
tes3.setPlayerControlState
tes3.wakeUp
tes3.getVanityMode
tes3.setVanityMode

**Comment by C3pa** [comment]
tes3.mobilePlayer is present in documentation. Events listed here are added in #301.

**Comment by C3pa** [comment]
Wasn't tes3weapon documented in #53?

**Comment by C3pa** [comment]
There was some work on this. Still missing:

'include' function

Types:
tes3weapon
tes3mobileActor.isDead
tes3skill
tes3.player.object.factionIndex
tes3reference:disable()
tes3reference:enable()
tes3reference.destination

Tes3ui API:
tes3ui.updateEnchantingMenu()
tes3ui.updateSpellmakingMenu()
tes3.mobilePlayer:updateOpacity()
tes3ui.refreshTooltip()
tes3ui.showInventorySelectMenu

Mwscript API:
mwscript.setDelete

Tes3 API:
tes3.worldController
tes3.getVanityMode

**Comment by C3pa** [comment]
tes3.player.object.factionIndex is depracted. Use tes3.player.object.reputation

**Comment by C3pa** [comment]
Since the .factionIndex field is depracted and replaced with .reputation, it doesn't need documenting. mwscript.setDelete won't be documented. At least for now.
