### ISSUE TITLE
Can't get actor's reputation

### ISSUE THREAD

**Issue by qqqbbb** [MWSE/MWSE#213]
This is always 0
`tes3.player.baseObject.reputation`

**Comment by adituv** [comment]
It looks like, for the player, their reputation is stored in their factionIndex.  As a workaround, for now you can use `tes3.player.object.factionIndex` to access the player's reputation.

Maybe there should be special methods `tes3.{get,set}PCReputation` to handle this?

**Comment by C3pa** [comment]
Reputation will always be 0 on `tes3.player.baseObject`, use `tes3.player.object` to get the current reputation as adituv mentioned.
