### ISSUE TITLE
mouseButtonDown/Up events return nil for e.isAltDown, etc

### ISSUE THREAD

**Issue by svengineer99** [MWSE/MWSE#215]
**Describe the Bug**
mouseButtonDown/Up events return nil for e.isAltDown, e.isShiftDown, e.isControlDown

**To Reproduce**
local function onMouseButtonDown(e)
mwse.log("onMouseButtonDown e.button:%s, e.isAlt/Control/ShiftDown:%s/%s/%s", tostring(e.button), tostring(e.isAltDown), tostring(e.isControlDown), tostring(e.isShiftDown))
end
event.register("mouseButtonDown", onMouseButtonDown, { filter = 0 }) -- filter for left mouse button

**Expected Behavior**
true or false return values

**Screenshots**

**MWSE Log File**
onMouseButtonDown e.button:0, e.isAlt/Control/ShiftDown:nil/nil/nil

**Additional Context**
NA

**Comment by C3pa** [comment]
Resolved by: https://github.com/MWSE/MWSE/commit/f78c239a852d0209edf665658865969962ce295b
