### ISSUE TITLE
enterFrame timestamp data

### ISSUE THREAD

**Issue by svengineer99** [MWSE/MWSE#216]
**Is your feature request related to a problem? Please describe.**
not really, just convenience and consistency with the simulate event.  actually i thought it was a bug looking at old docs, then realized the data had been dropped, maybe for some good reason?  if so then, ignore, obviously.

**Describe the solution you'd like.**
e.timestamp returns the same as for the simulate event:
Number. Read-only. The number of seconds since the beginning of the 3rd Era. (similar to the Unix Epoch)

**Describe alternatives you've considered.**
adding up e.delta

**Additional context.**
NA

**Comment by OperatorJack** [comment]
Fixed in commit eca4a32e04117f05c168c6e7d2ebc116dcc09886.

Example:
```lua
local function func(e)
	mwse.log(e.timestamp)
end

event.register("enterFrame", func)
```
