### ISSUE TITLE
tes3.getLanguage and tes3.getLanguageCode do not work for french version of the game

### ISSUE THREAD

**Issue by qqqbbb** [MWSE/MWSE#219]
tes3.getLanguage  returns 'eng' .
tes3.getLanguageCode returns 0.

**Comment by MetaBarj0** [comment]
Noticed the issue too, make sure to use tes3.getLanguage() after certain events had triggered. For instance, it works well if you call it after "modConfigReady" event has triggered (for mcm usage)
