### ISSUE TITLE
editing barterGold doesn't work

### ISSUE THREAD

**Issue by strelocc** [MWSE/MWSE#225]
inside an activate event e.target.object.barterGold returns the corrct value, but editing it has no effect, tried also saving/reloading/changing cell

**Comment by qqqbbb** [comment]
You should edit base object before its reference is created.
This kind of works `reference.mobile.barterGold = 11` but only if you talked to the NPC.

**Comment by OperatorJack** [comment]
As **qqqbbb** said, editing the base object will not update any existing references. You can update the reference's barter gold separately.
