### ISSUE TITLE
Getting calculated speed from mobile actor

### ISSUE THREAD

**Issue by qqqbbb** [MWSE/MWSE#227]
`mobile.runSpeed`, `mobile.walkSpeed`, `mobile.flySpeed`, `mobile.swimRunSpeed` and `mobile.swimSpeed` return the same value.

this crashes the game
`mobilePlayer.moveSpeed`

**Comment by C3pa** [comment]
All of the mentioned properties now work, and `tes3.mobilePlayer.moveSpeed` doesn't crash.
