### ISSUE TITLE
xSpellList missing race/birth inherited spells, CTD before adding one non-inherited one

### ISSUE THREAD

**Issue by svengineer99** [MWSE/MWSE#24]
With no in-game added spells (just inherited from birth/race) xSpellList crashes on call.  After adding 1 or more spells, including powers or abilities, the function works except it doesn't return the inherited ones.  0.9 MWSE had the same limitation but no CTD.  Test script below.

begin test_xspelllist

long pc_ref
long l1
long l2
long l3
long l4
long sp_id
long sp_ty
long sp_cst
long nxt_ref
long l5

setx pc_ref to xgetref "player"
set nxt_ref to 0
setx l1 sp_id l2 sp_ty sp_cst l3 l4 nxt_ref to pc_ref->xspelllist nxt_ref
whilex ( l1 ) 
	xlogmessage "test_xspelllist %d %s %s %d %d %d %d %d" l1 sp_id l2 sp_ty sp_cst l3 l4 nxt_ref
	ifx ( nxt_ref )
		setx l5 sp_id l2 sp_ty sp_cst l3 l4 nxt_ref to pc_ref->xspelllist nxt_ref
	endif
	set l1 to ( l1 - 1 )
endwhile

stopscript test_xspelllist
end

**Comment by NullCascade** [comment]
Crash fixed in 79d683fdc6aa4e2dce19237462fb0df7649a685e.

Inherited data must live elsewhere. Going to punt on exposing such to Lua instead of via xSpellList.

Thank you for the bug report. :)

**Comment by svengineer99** [comment]
Thanks!
