### ISSUE TITLE
[wine compatibility] Can't load MSVCRT.dll heap function through dbghelp.dll 

### ISSUE THREAD

**Issue by llde** [MWSE/MWSE#242]
Hi, with another linux user we were trying to allow, MWSE to work under wine.
https://bugs.winehq.org/show_bug.cgi?id=47940

While MGE XE issue can be workarounded easily, MWSE fail to start with a Can't find malloc error.

MWSE use Dbghelp functions to get malloc/realloc/free addresses from MSVCRT.dll

However dbghelp return the symbols as MSVCRT_malloc MSVCRT_realloc and MSVCRT_free.
Stangely enough as in the MSVCRT.spec file the public symbols are defined correctly.

It should be possible to allow MWSE to check also for the prefixed function? While I made a quick hack to strip the prefix, that allow MWSE to work (albeit didn't test it fully), it require people to recompile wine every time, as something like that will never be suited into inclusion by wine or wine-staging devs.

Also if may I ask, what was the rationale for using dbghelp functions to get MSVCRT  functions, instead of using GetProcAddress  to obtain them or directly the Winapi Heap functions ?

(Unluckly it seems that native MSVCRT can't work as it forward to ucrtbase.dll and it's a can of worm work with it)

**Comment by NullCascade** [comment]
I've switched to direct address binding for `malloc`, `free`, and `realloc`. like we do for most of our hooks in 793cfb91b58216390d7f7bfbcdc7ffb6de55084b.

We unfortunately can't just use the ones defined in the header files as they are incompatible (e.g. using a normal `free` on memory `malloc`ed by Morrowind.exe will cause a crash). So we need to grab the older versions.

Another blocker for Wine compatibility I believe is the legacy mwscript text input commands (`xTextInput` and `xTextInputAlt`). My memory is a bit fuzzy here but IIRC Wine doesn't support `GetAsyncKeyState`, or has/had issues with it. There's a test .esp file in this project that may have test cases for those functions, or you can try a mod that uses it if it interests you. This is less likely to change or be fixed, as legacy support for mwse-mwscript is largely abandoned in favor of work on mwse-lua.

**Comment by llde** [comment]
Using GetProcAddress would probably have been enough.  And probably would be better in case of strange msvcrt.dll relocation.
