### ISSUE TITLE
Implement stealth check event

### ISSUE THREAD

**Issue by MortimerMcMire** [MWSE/MWSE#252]
https://wiki.openmw.org/index.php?title=Research:NPC_AI_Behaviour#NPC_awareness_check

"This check runs every 5 seconds for each NPC. It occurs whether you are sneaking or not, but isn't the same as the combat distance check."

being able to flag the player as "seen" or "not seen" by each npc would be fantastic

**Comment by OperatorJack** [comment]
Added lua event to MWSE to set if player, or other actors, is detected by a given NPC per detection check.
