### ISSUE TITLE
soundPlay and soundPlayed events

### ISSUE THREAD

**Issue by JaceySanders** [MWSE/MWSE#275]
MWSE currently has the capability to stop a sound from playing by using tes3.removeSound, but it is difficult to get it to trigger at the right time. For example, say you want to prevent the potion drinking sound for a particular potion -- running tes3.removeSound off of the triggers of the equip or equipped events does not work. Likewise, if you want to remove the spell effect application sound for a particular source, running tes3.removeSound of of the magicCasted does not work. The only way I have found to actually use the tes3.removeSound function is by running it on simulate for a period of time around when I expect the sound to play, though that is unreliable, and not ideal for performance.

**Comment by C3pa** [comment]
Have you tried using any of these: [soundObjectPlay ](https://mwse.readthedocs.io/en/latest/lua/event/soundObjectPlay.html) or [playItemSound](https://mwse.readthedocs.io/en/latest/lua/event/playItemSound.html)?

**Comment by JaceySanders** [comment]
Those were added since I filed this request. Thanks! I will close it out.
