### ISSUE TITLE
inventoryChanged event

### ISSUE THREAD

**Issue by JaceySanders** [MWSE/MWSE#280]
**Is your feature request related to a problem? Please describe.**
I am having trouble making my gold weight mod more performant, and in expanding it to actors beside the player. Currently I have two working ways of doing it: run the function every enterFrame, or tie it to the itemTileUpdated event, which only applies to the player, and which requires extra handling for dropping items.

**Describe the solution you'd like.**
A new event, inventoryChanged, which fires whenever the inventory of any actor changes. Ideally, it would return the actor whose inventory it is, the itemStack that changed, and the current and previous state of that itemStack.

**Describe alternatives you've considered.**
I tried finding all of the actors in active cells and getting their inventories so that I can check them each frame, but it crashed, and it seems likely to be a performance nightmare that way.

**Comment by C3pa** [comment]
Isn't this esentially the same as: https://github.com/MWSE/MWSE/issues/206

**Comment by JaceySanders** [comment]
Yes, substantially.
