### ISSUE TITLE
Undocumented Event Data for "damage".

### ISSUE THREAD

**Issue by JaceySanders** [MWSE/MWSE#299]
There is at least one undocumented event data for the damage event: e.source

**Comment by C3pa** [comment]
Added in #296. It's currently in autocomplete files, you can read about it there. For it to show on [https://mwse.readthedocs.io/en/latest/lua/api/mwse.html](https://mwse.readthedocs.io/en/latest/lua/api/mwse.html), documentation has to be regenerated.

**Comment by C3pa** [comment]
This can be closed now
