### ISSUE TITLE
Undocumented methods element:registerBefore and element:registerAfter

### ISSUE THREAD

**Issue by JaceySanders** [MWSE/MWSE#304]
Mentioned by Null here:
https://discordapp.com/channels/210394599246659585/381219559094616064/847015585816379422

Missing from documentation here:
https://mwse.readthedocs.io/en/latest/lua/type/tes3ui/element.html?highlight=createBlock

**Comment by JaceySanders** [comment]
Oh, I may have been using the old orphaned element page. Here is the proper one:
https://mwse.readthedocs.io/en/latest/lua/type/tes3uiElement.html
Still missing the methods, though.

**Comment by Hrnchamd** [comment]
Added to tes3uiElement page in 02fa5fb5fc97b4e8721bc829583e86eb5a8bf862. The page is still messy, the register method description should be its own page.
