### ISSUE TITLE
When in MCM, right click exits menu mode without closing the menu

### ISSUE THREAD

**Issue by JaceySanders** [MWSE/MWSE#312]
**Describe the Bug**
When in MCM, right click exits menu mode without closing the menu. The menu is then unable to be closed without loading another save, or restarting the game.

**To Reproduce**
Open the options menu (default Escape), click "Mod Config", toggle menu mode (default right click). The game unpauses, and you can look around, but the menu is still present. If you go back into menu mode (right click again), you can interact with the Mod Config menu, but you can't close it.

**Expected Behavior**
Either
1. toggle menu mode should be disabled, so right clicking does nothing, 
2. toggle menu mode closes the menu and then exits menu mode
3.  The MCM remains open, but is interactable when returning to menu mode.

**Comment by Hrnchamd** [comment]
Should be fixed with commit 39a140.

**Comment by JaceySanders** [comment]
It is fixed! Thanks!
