### ISSUE TITLE
tes3.getCurrentAIPackageId() returning -1 for followers

### ISSUE THREAD

**Issue by GreyWyvern** [MWSE/MWSE#313]
The tes3.getCurrentAIPackageId(actor) function is returning -1 for actors who have tes3.aiPackage.follow (3). I'm not sure if this holds true for actors with other AIPackages. This issue is breaking the Easy Escort mod for some months now.

**Comment by NullCascade** [comment]
The use of that function is:
```lua
tes3.getCurrentAIPackageId({ reference = actorRef })
```
Most `tes3.*` API functions use table parameters.
