### ISSUE TITLE
Crash Script: fl_ig_global (Protective Guards.esp)

### ISSUE THREAD

**Issue by B00ze64** [MWSE/MWSE#318]
**Describe the Bug**

MW crashes sometimes with the following in the MWSE log. It is hard to reproduce, happens in combat at sea (Mudcrab Island's ambush while using the ship) with a lot of Abot's fishes in the water. I do not see a minidump.

**MWSE Log File**

Morrowind has crashed!
MWSE version: 2.1.0-1592
Build date: 20210620
Memory usage: 1587146752 bytes.
Lua traceback at time of crash:
stack traceback:
Currently executing mwscript context:
  Script: fl_ig_global (Protective Guards.esp)
12a1da58 90 a9 74 00 53 43 50 54 0a 00 00 00 a0 7a 5a 0b  ..t.SCPT.....zZ.
12a1da68 66 6c 5f 69 67 5f 67 6c 6f 62 61 6c 00 00 00 00  fl_ig_global....
12a1da78 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
12a1da88 02 00 00 00 08 00 00 00 01 00 00 00 40 09 00 00  ............@...
12a1da98 43 00 00 00 e0 31 9a 12 68 67 91 12 70 31 9a 12  C....1..hg..p1..
12a1daa8 08 d7 77 12 00 00 00 00 40 20 aa 12 a0 31 9a 12  ..w.....@ ...1..
12a1dab8 c0 64 91 12 d0 31 9a 12 00 00 00 00 00 00 00 00  .d...1..........
  Reference: fl_ig_global (Protective Guards.esp)
00000000

**Comment by NullCascade** [comment]
Old mwse-mwscript is limited.

Consider using [More Attentive Guards](https://www.nexusmods.com/morrowind/mods/48622) instead.

**Comment by B00ze64** [comment]
Hi NC, lol, mwse-script might be limited, but if there was a bug in it, you'd want to take a look. I have of course switched to More Attentive Guards by now, after seeing the MWSE process crashed repeatedly by Protective Guards. Anyway, this is reproducible, but it might just be a bug in Protective Guards, it kinda always happens when there's a ton of Abot's fishes around for some reason (and not a single guard for miles lol).
