### ISSUE TITLE
Unequip slot

### ISSUE THREAD

**Issue by Petethegoat** [MWSE/MWSE#32]
This is potentially difficult as there are two types of slot constant, the clothing type and armor type.

Optionally it could be split into unequipArmor and unequipClothing.

This might also be something to implement in pure Lua for the time being, with the equip dummy item, delete dummy item trick instead.

**Comment by jhaakma** [comment]
An unequip function in mwse/lua would be really helpful, or else we're forced to use the same trick as vanilla morrowind of equipping/removing a dummy item

**Comment by Petethegoat** [comment]
added in f920a00! thanks @Hrnchamd!
