### ISSUE TITLE
tes3.positionCell started ignoring teleportCompanions parameter; companions always teleport now

### ISSUE THREAD

**Issue by AsesinoBlade** [MWSE/MWSE#322]
**Describe the Bug**
tes3.positionCell in TES3UtilLua.cpp includes an optional Parameter to teleportCompanions when the reference is the player.   Until recently, I was able to use teleportCompanions = false to leave companions when traveling.   Now, it will always teleport the companions.

This functionality worked a couple of weeks ago, but I have run mwse_update nightly, and haven't used the positioncell in a while so I  don't know exactly which build changed the functionality.

thank you for your consideration.
a

**Comment by Hrnchamd** [comment]
The Easy Escort mod will teleport active companions to you in all cases, that's the most likely cause.

The tes3.positionCell function hasn't changed in about 12 months.

**Comment by AsesinoBlade** [comment]
Wow, you were right; it had nothing to do with this.  I installed Easy Escort back on July 7th and forgot about it.  I didn't think to check that another mod was moving my companions.  
Thank you so much!
a
