### ISSUE TITLE
Missing UI related things in the docs

### ISSUE THREAD

**Issue by C3pa** [MWSE/MWSE#334]
- tes3ui Types
Missing type directory: tes3uiButton
Missing type directory: tes3uiFillBar
Missing type directory: tes3uiParagraphInput
Missing type directory: tes3uiSlider
Missing type directory: tes3uiScrollPane
Missing type directory: tes3uiTextInput
Missing type directory: tes3uiTextSelect

Split from #332

**Comment by pierresteeg** [comment]
This should be fixed in 4b046367194dd1ea41d39c7f4a4c510fffe00c32. Please let me know if something isn't correct.

**Comment by C3pa** [comment]
Thanks!
