### ISSUE TITLE
Areas of the documentation that need to be elaborated upon.

### ISSUE THREAD

**Issue by C3pa** [MWSE/MWSE#337]
Here is a list of functions/fields/properties which don't have a description yet, but their use isn't obvious, so they need one:

- [x] tes3ui.showInventorySelectMenu()
- [x] tes3ui.showDialogueMessage()
- [x] tes3aiPlanner.nextOpenPackageIndex
- [x] tes3.uiMenuController.helpRoot
  .mainRoot
- [x] tes3splashControllerActiveSplash.age - What is this measured in? Is it seconds?
  .ageMax?
- [x] tes3splashController.bloodSplashDurations - What is this measured in?
  .bloodTextureProperties - Which type are the entries?
  .bloodTextures - Which type are the entries?
  .bloodMeshes - Which type are the entries?
- [x] tes3moon
- [x] tes3fader.updateMaterialProperty() - What about value parameter?
- [x] tes3projectileController.projectiles
- [x] tes3inventoryTile.type
- [x] tes3processManager.checkAlarmRadius()
  .checkPlayerDistance() 
- [x] tes3dialogue.type

Events:
- [x] addTempSound
- [x] playGroup
- [x] playItemSound
- [x] soundObjectPlay
- [x] filterInventorySelect
- [x] fadersCreated

**Comment by pierresteeg** [comment]
Let me know if the docs for that are alright, documenting the filter field was a bit messy.
