### ISSUE TITLE
calcJump

### ISSUE THREAD

**Issue by Safebox36** [MWSE/MWSE#338]
**Is your feature request related to a problem? Please describe.**
An event for when a jump is triggered with information relating to the vertical parameter passing to the mobile's velocity.

**Additional context.**
See other calc events and [OpenMW research](https://gitlab.com/OpenMW/openmw/-/wikis/development/research#on-jumping) on jumping.

**Comment by C3pa** [comment]
Implemented by Sephumbra in [03d9118](https://github.com/MWSE/MWSE/commit/03d9118caf2cac602d3f72964a3becc17510cd58).
