### ISSUE TITLE
Replace `type = "table"` with proper array type (e.g. `tes3weather[]`)

### ISSUE THREAD

**Issue by C3pa** [MWSE/MWSE#353]
Since, it is now supported by our documentation build system, we should go through these:

![image](https://user-images.githubusercontent.com/41503714/164556686-d05d8cde-e74b-47bd-9071-553788cdef0b.png)

and write the appropriate types. This will show up as proper links on the documentation page, and will also provide correct types for the autocomplete suggestions.

**Comment by NullCascade** [comment]
This tackles the ones I could find through most searching. If I didn't miss any, feel free to close the issue.

**Comment by C3pa** [comment]
Thanks for your work, but those are not all of them. Here are some I found:
https://mwse.github.io/MWSE/apis/mge/#mgegetweatherscattering
https://mwse.github.io/MWSE/apis/mge/#mgesetweatherscattering
https://mwse.github.io/MWSE/apis/string/#stringsplit
https://mwse.github.io/MWSE/types/tes3aiConfig/#traveldestinations
https://mwse.github.io/MWSE/types/tes3aiPackageWander/#idles
https://mwse.github.io/MWSE/types/tes3aiPlanner/#packages
https://mwse.github.io/MWSE/types/tes3alchemy/#effects
https://mwse.github.io/MWSE/types/tes3armor/#parts
https://mwse.github.io/MWSE/types/tes3bodyPartManager/#activebodyparts
https://mwse.github.io/MWSE/types/tes3bodyPartManager/#attachnodes
https://mwse.github.io/MWSE/types/tes3class/#attributes
https://mwse.github.io/MWSE/types/tes3class/#majorskills
https://mwse.github.io/MWSE/types/tes3class/#minorskills
https://mwse.github.io/MWSE/types/tes3class/#skills
https://mwse.github.io/MWSE/types/tes3clothing/#parts
https://mwse.github.io/MWSE/types/tes3creature/#attacks
https://mwse.github.io/MWSE/types/tes3creature/#attributes
https://mwse.github.io/MWSE/types/tes3creature/#skills
Also for creatureInstance,
https://mwse.github.io/MWSE/types/tes3directInputMouseState/#buttons
https://mwse.github.io/MWSE/types/tes3enchantment/#effects
https://mwse.github.io/MWSE/types/tes3faction/#attributes
https://mwse.github.io/MWSE/types/tes3faction/#ranks
https://mwse.github.io/MWSE/types/tes3faction/#reactions
https://mwse.github.io/MWSE/types/tes3faction/#skills
https://mwse.github.io/MWSE/types/tes3factionRank/#attributes
https://mwse.github.io/MWSE/types/tes3factionRank/#skills
https://mwse.github.io/MWSE/types/tes3gameFile/#masterfilesizes
https://mwse.github.io/MWSE/types/tes3gameFile/#masternames
https://mwse.github.io/MWSE/types/tes3gameFile/#masters
https://mwse.github.io/MWSE/types/tes3ingredient/#effectattributeids
https://mwse.github.io/MWSE/types/tes3ingredient/#effects
https://mwse.github.io/MWSE/types/tes3ingredient/#effectskillids
https://mwse.github.io/MWSE/types/tes3inputController/#inputmaps
Maybe https://mwse.github.io/MWSE/types/tes3leveledCreature/#list ?
Maybe https://mwse.github.io/MWSE/types/tes3leveledItem/#list ?
https://mwse.github.io/MWSE/types/tes3light/#color
https://mwse.github.io/MWSE/types/tes3magicSourceInstance/#sourceeffects
https://mwse.github.io/MWSE/types/tes3mobileActor/#activemagiceffectlist
https://mwse.github.io/MWSE/types/tes3mobileActor/#attributes
https://mwse.github.io/MWSE/types/tes3mobileActor/#effectattributes
https://mwse.github.io/MWSE/types/tes3mobileActor/#getactivemagiceffects
Similar for mobileCreature, mobileNPC, mobilePlayer, tes3npc, tes3npcInstance
https://mwse.github.io/MWSE/types/tes3mobilePlayer/#levelupperspecialization
https://mwse.github.io/MWSE/types/tes3mobilePlayer/#levelupsperattribute
https://mwse.github.io/MWSE/types/tes3mobilePlayer/#skillprogress
https://mwse.github.io/MWSE/types/tes3mobilePlayer/#skills
https://mwse.github.io/MWSE/types/tes3nonDynamicData/#activemods
https://mwse.github.io/MWSE/types/tes3nonDynamicData/#magiceffects
https://mwse.github.io/MWSE/types/tes3nonDynamicData/#skills

**Comment by C3pa** [comment]
There are more:
https://mwse.github.io/MWSE/types/tes3race/#baseattributes
https://mwse.github.io/MWSE/types/tes3race/#skillbonuses
https://mwse.github.io/MWSE/types/tes3reference/#attachments
https://mwse.github.io/MWSE/types/tes3region/#sounds
https://mwse.github.io/MWSE/types/tes3skill/#actions
https://mwse.github.io/MWSE/types/tes3spell/#effects
https://mwse.github.io/MWSE/types/tes3splashController/#activesplashes
https://mwse.github.io/MWSE/types/tes3splashController/#bloodmeshes
https://mwse.github.io/MWSE/types/tes3splashController/#bloodsplashdurations
https://mwse.github.io/MWSE/types/tes3splashController/#bloodtextureproperties
https://mwse.github.io/MWSE/types/tes3splashController/#bloodtextures
All the colors in tes3uiButton
https://mwse.github.io/MWSE/types/tes3uiButton/
https://mwse.github.io/MWSE/types/tes3uiMenuController/#fontcolors
All the colors in tes3uiTextSelect
https://mwse.github.io/MWSE/types/tes3uiTextSelect/
https://mwse.github.io/MWSE/types/tes3vfxManager/#data
https://mwse.github.io/MWSE/types/tes3weatherBlight/#blightdiseases

I didn't check the events, but this should cover almost all of the remaining ones.

**Comment by NullCascade** [comment]
Alright. 29aca2f87a7e27d4b8f9b077d8b8df139780c45c should fix just about all of these. Let me know if you find more.

**Comment by C3pa** [comment]
Thanks!
