### ISSUE TITLE
Add a tes3.palette constant table

### ISSUE THREAD

**Issue by pierresteeg** [MWSE/MWSE#354]
Currently tes3ui.getPalette() has a bunch of listed possible string values for its parameter.
We should probably just add a tes3.palette table for that and reference that it maps to the values in that table.

**Comment by pierresteeg** [comment]
The docs also mention that the values listed are "standard" color names, hinting that there might be more possible values. This is not the case. Those are all possible values for the function.

**Comment by C3pa** [comment]
Added in 8ee0f19.
