### ISSUE TITLE
Support for umlauts and similar characters?

### ISSUE THREAD

**Issue by Krschkr** [MWSE/MWSE#36]
This might be a Lua specific issue, but umlauts and similar characters (like ß) don't seem to be supported. 

Occurrence: Translating the configuration menu of 'sophisticated save system' for testing purposes to german. The magic cards font Morrowind uses supports these characters, but in this mod's configuration menu they are displayed as "A " or "AY". 

Example:
"schließen" became "schlieAYen"
"Zurück" became "ZurA ck"

In case an update to MWSE could add support for such characters that would ease making a translation meant to be published.

**Comment by NullCascade** [comment]
I'd need to get a foreign copy of the game for testing. Everything I've seen has no support for non-wide/non-unicode characters. I'd need to understand how Morrowind handles these data structures in foreign versions.

I'm reading online that mod compatibility between versions can be spotty. I'll have to look into this more and get back to you.
