### ISSUE TITLE
Add `charGenFinished` event

### ISSUE THREAD

**Issue by pierresteeg** [MWSE/MWSE#361]
Plenty of mods need to check for character generation completion before executing their logic. This often leads to lots of boiler plate timers to check the state of a global variable and is quite bothersome to do.

Some mods could also make use of a `charGenStateChanged` event or similar, given that they might want to show menus directly during the chargen process. We have already stored the global variable related to this as `TES3::WorldController::gvarCharGenState`.
What would be the best way to go about this?

**Comment by pierresteeg** [comment]
As stated by NullCascade in issue #130 there are additional problems with that. Checking it for only one variable like other lua mods are already doing is probably not going to be much of an issue. This could also be implemented in pure lua, although @NullCascade should probably chime in on whats the best way to apporach this is.

So far mods need to check it via enterFrame/simulate/timers, depends on how we even want to implement this.

**Comment by NullCascade** [comment]
I don't have a fantastic idea on how to handle this. Though I've been wanting to add some "common" mods to MWSE itself, to raise some new lua events in them. Things that are easier to do in lua than C, mostly, and that are useful to modders. For example, an event when the last page is opened in a book, when chargen is finished, etc.

That mod is probably best to also pair with some other features, like providing each character upon chargen being finished a unique identifier so people can store temp files using that id.

If someone wants to implement this in lua, we can do it in say `core\mwse\theCommonModName\main.lua`. For chargen, it can just do an enterframe and when the value goes from X to the finished state (-1?) it triggers the event and stores the unique id on the player data.

**Comment by pierresteeg** [comment]
Implemented in [4d15389](https://github.com/MWSE/MWSE/commit/4d153895b0298300eabdb210237864293b3fddd9).
I would add the unique id in another module, given that it should also affect old saves that have been loaded.
