### ISSUE TITLE
Sophisticated Save System: Autosave on first cellchange after chargen

### ISSUE THREAD

**Issue by Krschkr** [MWSE/MWSE#37]
The first auto save on cellchange performed after the chargen happens before the last tutorial messagebox pops up, which explains how to open the journal. When loading that save for the first time after launching Morrowind the textbox will appear, but menumode not be triggered properly. Therefore you can start moving and looking around although that messagebox is popped up. The general menu for loading etc. can't be opened in that case. Luckily this issue is easily fixable by opening the inventory and then clicking OK in the tutorial messagebox.

It's hardly a relevant issue, but perhaps an autosave when using that final chargen door for the first time can be suppressed.

(If that issue can't be reproduced it may be somehow caused by my long loading times, I guess?)

**Comment by NullCascade** [comment]
This isn't MWSE-specific, but related to a MWSE mod. Moved here: https://github.com/NullCascade/morrowind-mods/issues/3
