### ISSUE TITLE
Sophisticated Save System: Save Thumbnails

### ISSUE THREAD

**Issue by Krschkr** [MWSE/MWSE#38]
Most save thumbnails of auto saves upon cellchange are just a solid colour block. Example:

https://www2.pic-upload.de/thumb/35462385/sssthumb.jpg

I have long loading times, so I suspect it may be caused by that and not be an issue with the mod itself.

**Comment by NullCascade** [comment]
Mod-specific. Moved here: https://github.com/NullCascade/morrowind-mods/issues/4
