### ISSUE TITLE
MWSE-Updater crash

### ISSUE THREAD

**Issue by Diomes2** [MWSE/MWSE#388]
The Bug -
MWSE-Update.exe crashes even when ran as administrator, and with Morrowind installed outside of default Programs folder. I'm Running Win-7 currently

To Reproduce -
I go to morrowind install folder, double click the MWSE-Update.exe, crashes and gets windows error message. "MWSE Auto-Updater has stopped working".  Checking problem details in windows ...WER\ReportArchive I can read the windows error record   ....(this is the abbreviated form).... 

Problem Event Name:	APPCRASH
  Application Name:	MWSE-Update.exe
  Application Version:	1.0.0.0
  Application Timestamp:	6297e619
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.23572
  Fault Module Timestamp:	57fd0379
  Exception Code:	e0434352
  Exception Offset:	0000c54f
  UI[2]=C:\Program Files (x86)\Bethesda Softworks\Morrowind\MWSE-Update.exe
  UI[3]=MWSE Auto-Updater has stopped working
  UI[4]=Windows can check online for a solution to the problem.
  UI[5]=Check online for a solution and close the program
  UI[6]=Check online for a solution later and close the program
  UI[7]=Close the program
  LoadedModule[0]=C:\Program Files (x86)\Bethesda Softworks\Morrowind\MWSE-Update.exe
  LoadedModule[36]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\diasymreader.dll
  FriendlyEventName=Stopped working
  ConsentKey=APPCRASH
  AppName=MWSE Auto-Updater
  AppPath=C:\Program Files (x86)\Bethesda Softworks\Morrowind\MWSE-Update.exe
______________________________________________

In the MWSE-Update.exe window I can read

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.Compression, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
at MWSE.AutoUpdater.Main(String[ ] args) 
______________________________________________

My game worked/works fine I just wanted to update so I can play some of the newest mods. I think there are two things going on here. 

First - The AppPath appears to be looking in the wrong place. Not sure how to redirect its path, or why it's trying to path there.

Second - There was a problem even when Morrowind was in  \Program Files (x86) folder.     *read below*

A few years back I installed Morrowind in \Program Files (x86) with MWSE and hundreds of mods all working properly together, but earlier this week I decided to update MWSE using the updater and it didn't work. At first I assumed it was because I had such an old version of MWSE that the updater was obsolete/broken. I ignored it for a few days but, unhappy with my current mods, I decided I should just do a complete un-install of Morrowind and do a fresh re-install outside of the Program folder. It is now located in C:\Games\Morrowind

Looking back at the windows error reports, ".wer ReportArchive", the reports from earlier this week are 100%  identical (except for timestamps) to the more recent one I just posted above. Meaning as far as windows is concerned the problem is exactly the same as it was when Morrowind was installed in \Program Files (x86).

My first thought is that windows 7 doesn't like changes to Program Files, and that's why it originally failed, and now the AppPath location is wrong and I don't know how to fix it. 

Second thought is, why is the two windows error report identical? Could this also be a privacy setting I have set on my computer that blocks the .exe from accessing the internet? If it is, I'm not sure what that setting might be.

There is no MWSE.log file cause this is a fresh install. I could provide the two report.wer files, but I'm not sure if they contain personal information that I shouldn't be posting out in the open on the web.

Any thoughts on how to fix this will be greatly appreciated.  TY - Diomes2

![MWSE error](https://user-images.githubusercontent.com/111824508/186066346-94c9db55-8e8d-4c9d-adeb-cbe109972b28.jpg)

**Comment by C3pa** [comment]
Do you have Visual Studio x86 2022 Redistributable package installed? You can find a link to it [here](https://mwse.github.io/MWSE/).

In the meantime, you can update your mwse installation manually. [Here ](https://github.com/MWSE/MWSE#download-the-latest-nightly-build-here)is a link to the latest nightly build.

**Comment by Diomes2** [comment]
Ty for the response C3pa

I installed the Visual Studio x86 2022 Redistributable package, and manually installed the latest build from link you provided. I also fixed the Windows Registry to current game directory. No change, same exact error message as before. Both the MWSE-Update.exe window, and the Windows Error Reporting archive .wer file are 100% identical to what I originally posted. With the exception to the .wer file directory which now correctly states C:\Games\Morrowind where it should.

But, it is good to know that the "most recent build" is the most recent build and not just an old build with an updater.  TY - Diomes2

**Comment by feastsun** [comment]
Try to turn off UAC in Windows 7.

**Comment by Diomes2** [comment]
Ty feastsun for the response

I did that several different ways, the slider bar lowered, disable through gpedit.msc, disable through regedit, restart computer each time, and no change, same error message.

I think it has to be some configuration setting, which I can modify with the secpol.msc command, but I've just about killed my brain trying to find the source of this error.

Once I get all the lua mods running and the game running how I want it with save files and everything else that goes along with it, can I safely update this manually by overwriting with copy and paste, or would that really screw something up?  TY - Diomes2

**Comment by Diomes2** [comment]
I just read on another GitHub post-
"You need to use older python version (3.8). Python 3.9 and newer cannot be used on Windows 7 and earlier."
Is this part of the issue here? TY - Diomes2

**Comment by C3pa** [comment]
You don't need Python to run MWSE/MWSE updater.

**Comment by Diomes2** [comment]
Ty C3pa, but to the former question. 

Once I get all the lua mods running and the game running how I want it with save files and everything else that goes along with it, can I safely update this manually by overwriting with copy and paste, or would that really screw something up? TY - Diomes2

**Comment by C3pa** [comment]
Do you mean you want to update MWSE manually? Well, yes that is an entirely safe thing to do. Actually, that's just what the updater does 😉.

**Comment by Diomes2** [comment]
Awesome.. That's what I'll do then if I have to. 
I'm getting the same..ish problem with MLOX. Different error message but still fails to load. I'm fairly sure it's a security setting somewhere, or maybe a UAC control I'm overlooking, but I'm tired of looking for it atm.  

It's not on your guys end I'm sure of that, so I'll close this as resolved even thought it's not.... on my end anyway.

TY - for your patience
Diomes2
