### ISSUE TITLE
Adaptive filter entry field width

### ISSUE THREAD

**Issue by mojo187** [MWSE/MWSE#398]
A wonderful experience new CS is! My only nitpick for time being is filter entry field. It's a killer feature, but narrowing the object window (a common practice to make navigating through render window easier) makes it impossible to see what you're typing in filter field. Could it be made adaptive to the object window width?

![screenshot](https://user-images.githubusercontent.com/68021168/207798700-18b74033-7a97-4e21-b403-08b190e24eb8.jpg)
On this screenshot I've typed T_Com to navigate/

**Comment by NullCascade** [comment]
Fixed in 45c32bd674f421b6b079109ca4de9648fc262e91.
