### ISSUE TITLE
Hotkeys for Landscape Editor

### ISSUE THREAD

**Issue by MinerMan60101** [MWSE/MWSE#401]
**Describe the solution you'd like.**
The landscape editor has only two hotkeys you can use in the render window, `H` to close and open it, and `O` to toggle edit colors mode. I would like hotkeys to independently toggle "Smooth Vertices" and "Flatten Vertices", as well as hotkeys to increase and decrease the edit radius by increments of 1. For the latter, I think `[` to decrease and `]` to increase would work, which is how photoshop/GIMP change brush size (the order I listed should be used; English and other European languages are read right to left, so intuitively right is decreasing and left increasing for the majority of CS users). Pressing and holding should accelerate up or down until an extreme is hit.

**Describe alternatives you've considered.**
You could use one key to toggle between default/smooth/flatten, but flatten vertices is extremely destructive and undesirable to use in most cases of landscape editing so I would caution against this.

**Additional context.**
Flatten and Smooth are mutually exclusive, but both of them can be disabled to use the default landscape edit type.
1 is the minimum edit radius, and 30 is the maximum edit radius. (the CS resets it to 1 if you enter in 0 manually, and to 30 if you enter a value greater than 30 manually.)

**Comment by NullCascade** [comment]
Alright, should be good. Let me know if there are any issues. New hotkeys:
`[`, `]`: Decrement/increment edit radius.
`F`: Flatten vertices
`S`: Soften vertices.

Additionally, using `O` will no longer cause oddities with the landscape window, desyncing check enabled states.
