### ISSUE TITLE
Replace Dialogue Filtering option conflicts with MWSE Hide the Skooma mod

### ISSUE THREAD

**Issue by DSeyka** [MWSE/MWSE#426]
**Describe the Bug**
Whenever the Replace Dialogue Filtering option is enabled in Mod Config » Morrowind Script Extender, [MWSE Hide the Skooma](https://www.nexusmods.com/morrowind/mods/48454) mod works incorrectly, allowing you to trade illegal items with any vendor.

**To Reproduce**
1. Install [MWSE Hide the Skooma](https://www.nexusmods.com/morrowind/mods/48454) mod.
2. Make sure the Replace Dialogue Filtering option is enabled in Mod Config » Morrowind Script Extender.
3. Have skooma and/or moon sugar in your inventory.
4. Talk to Arille in Seyda Neen, note he doesn't care about illegal items in your inventory and will gladly trade them.
5. Disable Replace Dialogue Filtering option.
6. Talk to him again, note the mod is working properly now.

**Expected Behavior**
I would expect the mod to work alongside the Replace Dialogue Filtering option.

**MWSE Log File**
[MWSE.log](https://github.com/MWSE/MWSE/files/11912003/MWSE.log)

**Comment by NullCascade** [comment]
Should be fixed in 49079875cbc8b50c3cbb2c1b555584414b2f8254. Please let me know if you find further issues with the replaced dialogue filtering in builds [3264](https://ci.appveyor.com/project/NullCascade/mwse/builds/47439214) or later.
