### ISSUE TITLE
Reproducible crash when activating Ald-ruhn FG Dummy

### ISSUE THREAD

**Issue by abiel0530** [MWSE/MWSE#43]

**Comment by abiel0530** [comment]
I've Memory Monitor, Proportional Progression, SSS, Happy Harvesting, Expeditious Exit, Easy Escort, Diligent Defenders, Putting Power in Willpower, Discord Rich Presence, Torch Hotkey, Lucky Strike and Vaba-Amus.

**Comment by NullCascade** [comment]
@Petethegoat @abiel0530 Are you still able to reproduce this?
