### ISSUE TITLE
Claim effect ids 3300-3308 | Mod: Summon Souls

### ISSUE THREAD

**Issue by GreatOverlordMasterofAll** [MWSE/MWSE#434]
**What is the text identifier for the effect? This is the first param to `tes3.claimSpellEffectId`.**
storeSoul
summonSoul1
summonSoul2
summonSoul3
summonSoul4
summonSoul5
summonSoul6
summonSoul7
summonSoul8
**What is the numeric identifier for the effect? This is the second param to `tes3.claimSpellEffectId`.**
3300
3301
3302
3303
3304
3305
3306
3307
3308
**What is the name of your mod?**

Summon Souls

**Where can your mod be downloaded?**

https://www.nexusmods.com/morrowind/mods/53418

**Comment by C3pa** [comment]
Thanks for reaching out. The claimed effects were documented in https://github.com/MWSE/MWSE/commit/e09f56babe48b62efdf3d8c91d4054ac86563fd5.
