### ISSUE TITLE
Creature Sleep Interrupt mechanics exposed

### ISSUE THREAD

**Issue by Reizeron** [MWSE/MWSE#50]
Could we have the Creature Sleep Interrupt mechanic exposed? Hopefully with an ability to fire these events at will at any time.

**Comment by NullCascade** [comment]
I've added two events:

- [calcRestInterrupt](https://mwse.readthedocs.io/en/latest/lua/event/calcRestInterrupt.html)
- [restInterrupt](https://mwse.readthedocs.io/en/latest/lua/event/restInterrupt.html)

Please let me know if these don't satisfy your use cases. These will let you force/prevent interrupts, as well as dictate what creature is spawned.
