### ISSUE TITLE
Manually trigger crimes events

### ISSUE THREAD

**Issue by jhaakma** [MWSE/MWSE#55]
As a modder, I would like a way to trigger crimes, both preset crimes (tresspassing), or custom bounty amounts.

**Comment by MortimerMcMire** [comment]
I think the two key features in this would be 
1. modifying player bounty status
2. triggering 'detected a crime' status on npcs.

both of which would be very useful

**Comment by NullCascade** [comment]
92ecab903659bcb55b2b197c6510cef5d659d10b provides the first version of `tes3.triggerCrime()`.

In this example, we pretend the player stole the item he's looking at:
```lua
local function onUKey(e)
    local target = tes3.getPlayerTarget()
    if (target == nil) then
        return
    end

    local owner = tes3.getOwner(target)
    if (owner) then
        tes3.triggerCrime({
            type = 5,
            victim = owner,
            value = target.object.value,
        })
    end
end
event.register("keyDown", onUKey, { filter = 22 })
```
Valid types are Attack (1), Killing (2), Stealing (3), Pickpocket (4), Theft (5), Tresspass (6), Werewolf (7).

I'm going to let this settle for a day or two before writing up docs. Let me know if this works.

As before, manually changing bounty can be done by modifying `tes3.mobilePlayer.bounty`.
