### ISSUE TITLE
lua control over container / item popup window

### ISSUE THREAD

**Issue by MortimerMcMire** [MWSE/MWSE#67]
maybe this is an event? 

specifically, I would use this to completely hide container windows (the ones that say "Small Chest, Locked") and incorporate all of that data into my quickloot popup.

**Comment by Petethegoat** [comment]
This tooltip:
![image](https://user-images.githubusercontent.com/734762/42838691-125090e0-89c7-11e8-9ba5-419591eb6730.png)

**Comment by Petethegoat** [comment]
It doesn't trigger uiCreated.

**Comment by NullCascade** [comment]
No longer necessary.
