### ISSUE TITLE
Folder Restructure

### ISSUE THREAD

**Issue by NullCascade** [MWSE/MWSE#68]
The new folder structure will be:

- **Data Files/MWSE**: Files will be moved out of the lua subfolder and into the root MWSE folder.
  - **config**: The preferred location for mods to install their config files.
  - **core**: The folder that MWSE core libraries will be placed. This folder will be deleted and recreated with the auto-updater.
  - **libs**: A folder for 3rd party libraries that multiple mods might share, such as XML loaders. Libraries MWSE requires should still go in **core** so that they are updated or changed cleanly.
  - **mods**: The folder mods belong in.

The package lookup path will be modified to be the following:

- **./** -- For DLL files only.
- **./Data Files/MWSE/core/**
- **./Data Files/MWSE/libs/**
- **./Data Files/MWSE/mods/**

Finally, _mod_init.lua_ scripts will be renamed to _main.lua_.

@Greatness7 @Petethegoat

**Comment by Petethegoat** [comment]
`main.lua`s that are loose in MWSE/mods shouldn't run- we should enforce that they be in a subfolder, just to head off any silly problems.

**Comment by NullCascade** [comment]
In e105fa34603ec653e78708e554ea4ec4b22dbd7f I've changed so that legacy mods in mod_init.lua will only be accepted in **Data Files/MWSE/lua**. I think the only mod released that this affects is [Glow in the Dahrk](https://www.nexusmods.com/morrowind/mods/45886?). The lookup is now done in order, rather than being blanket thrown at the MWSE folder. The order of folders searched through is:

* **./Data Files/MWSE/core/** -- For main.lua files.
* **./Data Files/MWSE/mods/** -- For main.lua files.
* **./Data Files/MWSE/lua/** -- For mod_init.lua files.
