### ISSUE TITLE
Function to set attack hit to 'true'

### ISSUE THREAD

**Issue by MortimerMcMire** [MWSE/MWSE#71]
For instance, if I wanted to ensure that every attack would hit, I just need a variable or function I can change to 'true' to cause on-hit effects and damage to trigger.

Whatever that value is that's rolled to determine if an attack hits, where it takes into account fatigue and agility and weapon skill, then says "Yes you hit, calculate damage now" <- that's the value I want to be able to trigger.

**Comment by OperatorJack** [comment]
This functionality is available through the `calcHitChance` event. You can view the calculated hit chance and modify it as needed.

[You can view the documentation here.](https://mwse.readthedocs.io/en/latest/lua/event/calcHitChance.html)

We are cleaning up issues without recent activity, so if this does not answer your questions, please let me know and I will reopen the issue.
