### ISSUE TITLE
Armor Rating hook

### ISSUE THREAD

**Issue by Petethegoat** [MWSE/MWSE#74]
It'd be cool to get a hook when the armor rating is calculated (on player, NPCs, etc).

Not sure what event data you'd want. Reference and final rating, obviously.
A table with all the pieces of armor that were factored into the rating?
Or maybe the event fires for each piece as it's factored in?
The first way would probably be cleaner, I dunno.

The usage I have in mind is making all armor give it's basic armor rating to the wearer, regardless of skill level in that armor class.
(Then making skills or lack thereof add penalties for wearing armor).

**Comment by NullCascade** [comment]
I can do both or either. I can give you an event for when an item's AR is calculated, or when the total AR for the actor is calculated. Do you want both or just one?

**Comment by Petethegoat** [comment]
It wouldn't hurt to have both, as far as I can see.

**Comment by Petethegoat** [comment]
"calcArmorRating" now exists

could use docs though

**Comment by OperatorJack** [comment]
Documentation can be found [here](https://mwse.readthedocs.io/en/latest/lua/event/calcArmorRating.html).
