### ISSUE TITLE
Extend the equipment slot limit

### ISSUE THREAD

**Issue by jhaakma** [MWSE/MWSE#75]
I'd like the ability to unlock equipment slot limits (e.g. wear more than one belt). 

For example in the equip event, you could prevent the current item from being unequipped

**Comment by C3pa** [comment]
Now there are `tes3.addArmorSlot()` and `tes3.addClothingSlot`? Do these cover all your desired use cases?

**Comment by jhaakma** [comment]
Probably! Who know what I was trying to accomplish with this 5 years ago
