### ISSUE TITLE
ability to get actual used width of elements even when using autoWidth

### ISSUE THREAD

**Issue by MortimerMcMire** [MWSE/MWSE#76]
currently if you set an elements autoWidth == true and get its width, it doesn't return the actual width used, it returns its max width.

**Comment by NullCascade** [comment]
What happens after you do an `:updateLayout()` on the top-most element, then trying to get `.width`? It might be that the width isn't accurate because things haven't had time to rearrange.

**Comment by MortimerMcMire** [comment]
using .width after updateLayout correctly returns the width. For whatever reason it didn't back when I made this issue but it does now!
