### ISSUE TITLE
Improve some key-related functions

### ISSUE THREAD

**Issue by Greatness7** [MWSE/MWSE#78]
Remove `mwse.virtualKeyPressed(virtualKeyCode)` and replace it with a `tes3.isKeyPressed(keyboardScanCode)`. At the moment the mwse variant is the only input function that is not working with scan codes and as a result causes a bit of confusion. The other key functions `disableKey, enableKey, hammerKey, pushKey, releaseKey, tapKey, unhammerKey` already use scan codes. No mods have yet been released that use virtualKeyPressed, so it should be safe to deprecate.

Additionally: We need a way to convert scan codes to string representations for display. A `tes3.getKeyName()` that returns the GMST strings should be sufficient.

For both suggestions we may have to do special handling for mouse buttons as I believe scan codes do not cover them. (?)

**Comment by NullCascade** [comment]
I have the following written. Let me know if it meets expected use cases.

```lua
mwse.log("Keyboard state:")
for i = 0, 255 do
    mwse.log("    Key #%d (%s) is %s", i, tes3.getKeyName(i), (tes3.isKeyDown(i) and "down" or "up"))
end
```
This provides output like:
```
Keyboard state:
    Key #0 (nil) is up
    Key #1 (ESC) is up
    Key #2 (1) is up
    Key #3 (2) is up
    Key #4 (3) is up
    Key #5 (4) is up
    Key #6 (5) is up
    Key #7 (6) is up
    Key #8 (7) is up
    Key #9 (8) is up
    Key #10 (9) is up
    Key #11 (0) is up
    Key #12 (-) is up
    Key #13 (=) is up
    Key #14 (Back Space) is up
    Key #15 (Tab) is up
    Key #16 (Q) is up
    Key #17 (W) is up
    Key #18 (E) is up
    Key #19 (R) is up
    Key #20 (T) is up
    Key #21 (Y) is up
    Key #22 (U) is down
```

The following is added: `tes3.getKeyName`, `tes3.isKeyDown`, `tes3.isMouseButtonDown`. For `tes3.getKeyName`, instead of returning an empty string as Morrowind holds, it will return a value of `nil`.

---

There's also the matter of input bindings. We'll need a better API for that so that people can register their own input bindings. But that's outside the scope of this ticket. For now though we can iterate over them and get the key names doing:
```lua
mwse.log("Keybinds:")
local inputMaps = tes3.worldController.inputController.inputMaps
for i = 1, #inputMaps do
    local mapping = inputMaps[i]
    local mappingName = table.find(tes3.keybind, i-1)
    if (mapping.device == 0) then
        mwse.log("    %s is bound to %s", mappingName, tes3.getKeyName(mapping.code))
    elseif (mapping.device == 1) then
        mwse.log("    %s is bound to Mouse Button %d", mappingName, mapping.code)
    end
end
```
```
Keybinds:
    forward is bound to W
    back is bound to S
    left is bound to A
    right is bound to D
    use is bound to Mouse Button 0
    activate is bound to SPACEBAR
```

**Comment by Petethegoat** [comment]
Looks good so far! This is definitely a great start.

Are there any changes we can make now so it's easier to add proper controller support in the future?
Apart from that, there's nothing else that springs to mind that we need right now, other than custom bindings as you said.

**Comment by NullCascade** [comment]
3cd635846719bf60ce88bb76e68e62918f862cf7 brings in more information, pretty much completing the input controller data. This should open up gamepad axis and button events.

Before I add the functions I want to make sure the use cases we want are defined. Please let me know if I'm missing anything:

Input binding:
- See what bindings are used, including the id, device, and button/key/axis.
- Register new bindings.
- Get an event when my binding is used.
- Get current binding state.

Mouse:
- Get current button/axis state.
- Mouse button clicked events.
- Mouse axis movement events.

Keyboard:
- Get current key state.
- Key pressed/released events.

Gamepad:
- Button events.
- Axis events.
- Get current button/axis states.
- List the current devices.

The current proposal in Discord is to handle all action mappings by a table with `device` and `button` fields. These will be accessed by a string key:
```lua
local mapping = tes3.getInputMapping("activate")
-- Returns something like:
-- { device = tes3.device.keyboard, input = tes3.scanCode.enter }
```
This will let us register our own action mappings for mods too.

This table should be able to be fed to the functions declared above:
```lua
local device = tes3.getDeviceName(mapping) -- "keyboard"
local name = tes3.getInputName(mapping) -- "spacebar"
if (tes3.isInputDown(mapping)) then
    mwse.log("The %s button/key is down on the %s", name, device)
    -- "The spacebar button/key is down on the keyboard"
end
```
