### ISSUE TITLE
Improve xContentListFiltered

### ISSUE THREAD

**Issue by Greatness7** [MWSE/MWSE#8]
The "xContentListFiltered" function does not currently allow filtering for multiple item types. Adding such functionality would dramatically improve its usefulness.

A proposed solution is to use bitmasks for our filters rather than the type code directly. Other functions already in MWSE use similar behavior and work well enough. See: [xGetService](http://wiki.theassimilationlab.com/mmw/xGetService).

These are all types that can exist as references or container contents:

```
Type : Masks
------------
ACTI : 1
ALCH : 2
AMMO : 4
APPA : 8
ARMO : 16
BODY : 32
BOOK : 64
CLOT : 128
CONT : 256
CREA : 512
DOOR : 1024
INGR : 2048
LEVC : 4096
LEVI : 8192
LIGH : 16384
LOCK : 32768
MISC : 65536
NPC_ : 131072
PROB : 262144
REPA : 524288
STAT : 1048576
WEAP : 2097152
```

An example of how filtering for multiple types would look in mwscript:
```
begin GetAllApparel

long loop

long id
long count
long type
long value
float weight
long name

long next
long mask

set mask to ( 16 + 128 ) ; ARMO + CLOT

set loop to 1
whilex ( loop )
    setx id count type value weight name next to ref->xContentListFiltered next mask

    xLogMessage "id: %s" id
    xLogMessage "    count: %d" count
    xLogMessage "    type: %l" type
    xLogMessage "    value: %d" value
    xLogMessage "    weight: %.2f" weight
    xLogMessage "    name: %s" name
    xLogMessage "    next: %d" next

    set loop to next
endwhile

xStopScript 0

end
```

As a bonus, in the future filters for ENCH and SCPT could be included. Having these would make for significant performance boosts in many mods. Currently detecting enchanted/scripted items in loops requires 4 extra mwse calls per item, causing significant overhead when working with larger inventories.

**Comment by NullCascade** [comment]
Implemented in e29d05695e8850e1b89a3045ecc46c8f5caaf80d, allowing multiple filters.

Improved in 1ffe3fddc5a35a24f58bbe72df6e6a8874a1d855 to allow filtering on enchantments (either exclusively or in combination with record types).

Filtering by scripted items will have to be added at a later date, but the implementation will be able to be added at a later date.
