### ISSUE TITLE
mwscript.SetDisposition / moddisposition

### ISSUE THREAD

**Issue by MortimerMcMire** [MWSE/MWSE#82]
can't seem to change disposition on instanced NPC's without it. Can change the base record already, though.

**Comment by NullCascade** [comment]
This can be done with the base structures already:
```lua
local npc = mobileActor.reference.object
assert(npcClone.objectType == tes3.objectType.npc and npcClone.isInstance)
npc.disposition = npc.disposition + 20
```

Leaving open for simple `tes3.*` API functions in the future.
