### ISSUE TITLE
Play NPC voice function

### ISSUE THREAD

**Issue by MortimerMcMire** [MWSE/MWSE#84]
eg. when you steal an item they say "Guards!" or "Thief!"

The voices are all separated by topic, I assume they function like regular dialogue topics and pick the top response that meets the conditions.

**Comment by NullCascade** [comment]
Added in 1522c4b48c088ef0fdcbd6411888cb7b3d176a2d.

```lua
tes3.playVoiceover({ actor = someActor, voiceover = "thief" })
```
