### ISSUE TITLE
An event to change the armor piece that absorbs an attack, and change the damage reduced

### ISSUE THREAD

**Issue by jhaakma** [MWSE/MWSE#86]
An event that lets you change the armor piece that is chosen when attacked, and change the damage reduction of that armor

**Comment by jhaakma** [comment]
Any progress on this?

**Comment by Petethegoat** [comment]
"calcArmorPieceHit"
https://github.com/MWSE/MWSE/commit/294018ccd1aabba675de84d6833ca49fb88fa04a

**Comment by Petethegoat** [comment]
"calcArmorPieceHit"
https://github.com/MWSE/MWSE/commit/294018ccd1aabba675de84d6833ca49fb88fa04a
